feature(email notification): clin-394 - first draft - tasks extractor
Ferlab-Ste-Justine/clin-pipelines pull request #17
Opened 2021-11-23 03:42 UTC by evans-g-crsj

2021-11-23 13:27 UTC, jecos requested changes

2021-11-23 13:27 UTC, jecos commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.5.5","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/usr/lib/jvm/java-11-openjdk-amd64/bin/java","-Xms100m","-Xmx100m","-classpath","/home/egirard/.local/share/JetB
Add this file to .gitignore

2021-11-23 13:27 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/task/ldmnotifier/model/Task.scala
> +case class GqlResponse(data: Data)
Maybe I'm wrong but I don't think you need to redifne all implicates.

2021-11-26 19:39 UTC, botekchristophe commented on src/main/scala/bio/ferlab/clin/etl/task/ldmnotifier/TasksTransformer.scala
> +  private def retainOnlyDistinctUrlValuesForEachGroup(aliasToUrlsForAllTasks: Seq[AliasUrlValues] )= {
un espace en trop avant la ')' de fin et un manquant avant le '='

2021-11-26 19:39 UTC, botekchristophe commented on src/test/scala/bio/ferlab/clin/etl/fhir/testutils/FhirTestUtils.scala
> +      val parsedJson = Json.parse(strJson)
Json.parse() retourne quoi comme type ? ya peut être un facon plus rapide de transformer ca en Try[JsValue].
un genre de .toTry

2021-11-26 19:39 UTC, botekchristophe commented on src/main/scala/bio/ferlab/clin/etl/task/ldmnotifier/TasksGqlExtractor.scala
> +    (json).validate[GqlResponse].fold(
nice !

2021-12-01 22:16 UTC, evans-g-crsj commented on src/main/resources/application.conf
> +mailer {
Il manque des paramètres que l'on doit à la limite hardcoder: TLS=true, par exemple

2021-12-01 22:16 UTC, evans-g-crsj commented on src/main/scala/bio/ferlab/clin/etl/mail/MailerService.scala
> +      "subject",
sera modifié, évidemment.

2021-12-01 22:17 UTC, evans-g-crsj commented on src/main/scala/bio/ferlab/clin/etl/task/ldmnotifier/TasksMessageMaker.scala
> +    val file = new File("manifest.tsv")
je pense que je vais utiliser un createTempFile

2021-12-02 15:16 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/task/ldmnotifier/TasksTransformer.scala
> +      .groupBy(tupleAliasUrlValue => tupleAliasUrlValue._1)
deconstruct yor tuple or ue directly _._1

2021-12-02 15:16 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/task/ldmnotifier/TasksTransformer.scala
> +    val flattenedUrlValues = aliasToUrlsForAllTasks.flatMap(tupleAliasUrlValues => tupleAliasUrlValues._2)
deconstruct yor tuple or ue directly _._2

2021-12-02 15:16 UTC, jecos commented on src/main/scala/bio/ferlab/clin/etl/task/ldmnotifier/TasksGqlExtractor.scala
> +  def checkIfGqlResponseHasData(json: JsValue): Either[String, Boolean] = {
Maybe use ValidNel type from cats?

2023-06-07 20:19 UTC, closed without merging