Feat/clin 2056
Ferlab-Ste-Justine/clin-pipelines pull request #57
Opened 2023-07-07 17:28 UTC by ethienneroy

2023-07-07 17:29 UTC, ethienneroy commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.5.5","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Users/jecos/Library/Java/JavaVirtualMachines/corretto-11.0.18/Contents/Home/bin/java","-Xms100m","-Xmx100m","-c
ca fichier devrait pas etre la

2023-07-10 13:25 UTC, jecos approved these changes

2023-07-10 13:46 UTC, creativeyann17 requested changes

2023-07-10 13:46 UTC, creativeyann17 commented on src/main/scala/bio/ferlab/clin/etl/task/fileimport/model/Metadata.scala
> +case class SimpleMetadata(submissionSchema: Option[String], analyses: Seq[SimpleAnalysis]) extends Metadata
concerver les champs existants pour retro-compatiblite

2023-07-10 13:46 UTC, creativeyann17 commented on src/main/scala/bio/ferlab/clin/etl/task/fileimport/model/Metadata.scala
> +  def experiment: Experiment
mettre les nouveaux champs en optionel

2023-07-10 13:46 UTC, creativeyann17 commented on src/test/scala/bio/ferlab/clin/etl/task/fileimport/model/MetadataSpec.scala
> +      println(meta)
:)

2023-07-10 13:48 UTC, creativeyann17 commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.5.5","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Users/jecos/Library/Java/JavaVirtualMachines/corretto-11.0.18/Contents/Home/bin/java","-Xms100m","-Xmx100m","-c
Peux rajouter le repertoire a gitignore

2023-07-11 20:05 UTC, creativeyann17 requested changes
.gitignore + println

2023-07-14 16:40 UTC, merged